# Mission configuration
mission:
  # 起飞高度
  takeoff_altitude: 0.5
  
  # 任务序列
  actions:
    - type: "takeoff"
      altitude: 0.5
      
    - type: "land"

# 系统参数
system:
  use_camera_aim: true
  auto_start_mission: true  # 解锁后自动开始任务