# Mission configuration
mission:
  # 起飞高度
  takeoff_altitude: 0.5
  
  # 任务序列
  actions:
    - type: "takeoff"
      altitude: 0.5
    
    # - type: "move"
    #   position: [0.0, 0.0, 1.0]
    #   yaw: 0.0
    #   frame: "world_body"
    #   tolerance: 0.1
    
    - type: "land"

# 系统参数
system:
  use_camera_aim: true
  auto_start_mission: true  # 解锁后自动开始任务